pong:
  env_name: PongNoFrameskip-v4
  stop_reward: 18.0
  run_name: pong
  replay_size: 100000
  replay_initial: 10000
  target_net_sync: 1000
  epsilon_frames: 1e5
  epsilon_start: 1.0
  epsilon_final: 0.02
  learning_rate: 0.0001
  optim_params:
    eps: 1e-8
    weight_decay: 0.0
  gamma: 0.99
  batch_size: 32
  train_freq: 4
  gradient_clip: 10