pong:
  env_name: PongNoFrameskip-v4
  stop_reward: 18.0
  run_name: pong
  replay_size: 100000
  replay_initial: 80000
  target_net_sync: 32000
  epsilon_frames: 1e5
  epsilon_start: 1.0
  epsilon_final: 0.02
  learning_rate: 0.0000625
  optim_params:
    eps: 1.5e-4
    weight_decay: 0.0
  gamma: 0.99
  batch_size: 32
  train_freq: 1
  gradient_clip: 10
  logging_freq: 10 #unit: episodes
  reward_steps: 3
  prio_replay_alpha: 0.5
  beta_start: 0.4
  beta_frames: 100000
  noisy_nets_sigma: 0.5
  # C51:
  #  vmax: 10
  #  vmin: -10
  #  n_atoms: 51
